In [1]:
!pip install numpy pandas matplotlib

In [3]:
## LIBRERIAS

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

array es la funcion de crear matrixes donde uno puedo colacr un conjunto de objetos

In [12]:
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [13]:
vector = np.array([30,29,35,31,33,36,42]) #este es un diccionario
print(vector)


[30 29 35 31 33 36 42]


In [14]:
matrix = np.array([[1,2,3],[4,5,6,],[7,8,9] ])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [18]:
array_arange = np.arange(10) #que crea un array con una secuencia de números en un rango. En este caso, comienza desde 0 y llega hasta el número 10, pero sin incluirlo.
print(array_arange )

[0 1 2 3 4 5 6 7 8 9]


In [21]:
eye_matrix = np.eye(3) #Una matriz identidad es una matriz cuadrada que tiene unos (1) en la diagonal principal (de arriba a la izquierda hasta abajo a la derecha) y ceros (0) en todas las demás posiciones.
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
diag = np.diag([1,2,3,4,5,6,7])#este es la funcion diagonal
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]
