In [1]:
pip install numpy


In [2]:
import numpy as np

## Broadcasting

In [3]:
Prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = Prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [5]:
# Crear un array de precios aleatorios entre 100 y 500
prices = np.random.randint(100, 500, size=(3, 3))

# Crear un array de descuentos
discount = np.array([10, 20, 30])

# Aplicar el descuento utilizando broadcasting
discount_prices = prices - discount

# Mostrar los resultados
print("Precios originales:")
print(prices)
print("\nPrecios con descuento:")
print(discount_prices)


Precios originales:
[[171 478 359]
 [313 193 120]
 [165 497 349]]

Precios con descuento:
[[161 458 329]
 [303 173  90]
 [155 477 319]]


In [7]:
array = np.array([1, 2, 3, 4, 5])

# Verificar si todos los elementos del array son mayores que 9
print(np.all(array > 9))

False


In [9]:
array = np.array([1, 2, 3, 4, 5])

# Verificar si todos los elementos del array son mayores que 9
print(np.any(array > 4))

True


In [15]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Concatenar array_a y array_b
concatenated_a = np.concatenate((array_a, array_b))
concatenated_b = np.concatenate((array_a, array_b))

# Imprimir los arrays concatenados
print(concatenated_a)
print(concatenated_b)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [18]:
stacked_h = np.vstack((array_a, array_b)) # utiliza para apilar arrays verticalmente (es decir, fila sobre fila). El resultado es un array de mayor dimensión que incluye los arrays originales como filas

# Imprimir el array apilado
print(stacked_h)

[[1 2 3]
 [4 5 6]]


In [21]:
from posixpath import split

# Crear un array con valores del 1 al 9
array_c = np.arange(1, 10)

# Dividir el array en 3 partes iguales
split_array = np.split(array_c, 3) # divide el array array_c en 3 subarrays de igual tamaño.

# Imprimir el array original y los arrays divididos
print("Array original:")
print(array_c)

print("\nArrays divididos:")
print(split_array)

Array original:
[1 2 3 4 5 6 7 8 9]

Arrays divididos:
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
